### ISSUE TITLE
Enable URL change for Ollama

### ISSUE THREAD

**Issue by PierreMesure** [albertocubeddu/extensionOS#41]
**Is your feature request related to a problem? Please describe.**

I can't use my Ollama server because it's not running on localhost.

**Describe the solution you'd like**

Add a field to customise the base URL for Ollama.

**Comment by albertocubeddu** [comment]
Hi Pierre, I'm currently on holiday, I'll add the feature on Wednesday. 

Thank you for lodging the issue.

**Comment by albertocubeddu** [comment]
I apologise for the delay; American Airlines isn't the best company when they lose your luggage.

https://github.com/albertocubeddu/extensionOS/tree/0.0.24

Check this version, i've added this: 
<img width="675" alt="image" src="https://github.com/user-attachments/assets/3bfbf629-550c-4947-9c7b-c26721e844f2">

I wait until next week to publish it as I want to have a bit of time to think about the solution i've build.
